// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skksjxsfxuwtzwpujrpw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNra3NqeHNmeHV3dHp3cHVqcnB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0ODY0ODAsImV4cCI6MjA2OTA2MjQ4MH0.ONNKVp6V2foDfuwqZ0tojZIYAAksHCa6MEtpjB0CXaw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});